### ISSUE TITLE
Error in std_mpreclust: Reference to non-existent field 'comp30'

### ISSUE THREAD

**Issue by CorentinWicht** [sccn/mp_clustering#1]
Dear EEGLAB developpers,

I am reporting here an issue related to the `std_mpreclust` function (in EEGLAB .

When running `STUDY = std_mpreclust(STUDY,ALLEEG, {'dipole' ,'spec' ,'map'}, true)` I get:
![image](https://user-images.githubusercontent.com/52161904/117273064-1192f500-ae5c-11eb-901d-a2f686c3af09.png)

Digging deeper into the error, I found out that the issue begins in `std_readdata.m`, **line 186**:
`compList = [ compList STUDY.cluster(opt.clusters).comps(indSet) ];`

`compList` is a concatenation of components list one specific subject at a time, across the within-subject factor levels "conditions" (in my case, a vector of length 105 of the form `[1:29 1:37 1:39]` since I have 3 conditions {"S1","S2","S3"}). 

Then this `compList` is used as an argument in **line 218** to call `std_readfile.m`:
`else [dataTmp{iSubj}, params, xvals, yvals, eventsTmp{iSubj} ] = std_readfile( fileName, 'designvar',struct(bigstruct.design.variable), opts{:}, 'components', compList);`

When going through each iteration of the error I reached the **for loop lines 335-400** (still in `std_readfile.m`) and I see that the errors come from the structure `fileData` that only contains information for the first 29 components (while the `compList`, which is now called `chan` is still of length 105):
![image](https://user-images.githubusercontent.com/52161904/117275504-67689c80-ae5e-11eb-9b86-1b471611aba8.png)

There is a conceptual issue here I think, because if `fileData` contained one structure field for each of the concatenated components indexes in `compList` as would be expected, some fields would have the same name. Indeed, since the independent component 1 exists in all 3 conditions of my subject, the field "comp1: [513x641]" could be related to any of these 3 conditions. 

By the way, I don't know maybe if the error could also be related to the `designvar` variable :
![image](https://user-images.githubusercontent.com/52161904/117277282-08a42280-ae60-11eb-9db4-febd7d05d280.png)

In `std_readfile.m`, **line 299**, I have trouble understanding why you are retrieving `designvar(2:end)` ?:
` [ tmpMeasureData, tmpEvents ] = globalgetfiledata(fileData, designvar(2:end), options, trialselect);`
This ultimately leads, in my case to a `1×0 empty struct array with fields`.

I hope my explanations were clear enough, let me know if you would need data to reproduce the error.

**Comment by CorentinWicht** [comment]
In case here is the [link to download the dataset](https://www.dropbox.com/s/db68rha7fqj5g83/Dataset.mat?dl=0) I used.

**Comment by arnodelorme** [comment]
Hi Corentin, unfortunately, this repository is not supported and we do not have the resources to do so. 

In this case, it might be because your subjects have a different number of components and this is not supported by the plugin (the specific data you sent does not have a component 30). Also, you might want to recompute the component files or make sure all subjects have the same number of components.
